### ISSUE TITLE
Fix node crash if mdw or node request fails

### ISSUE THREAD

**Issue by earlyriser99** [aeternity/ae_canary#21]
Crash log:

```
app                |     (stdlib 3.14.1) gen_server.erl:744: :gen_server.handle_msg/6
app                |     (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
app                | Last message (from #PID<0.651.0>): {:exec, #Function<0.85613849/0 in AeCanary.Mdw.Cache.Service.Exchange.refresh_data/1>}
app                | 12:16:37.715 [error] Task #PID<0.651.0> started from AeCanary.Mdw.Cache.Service.Exchange terminating
app                | ** (stop) exited in: GenServer.call(#PID<0.649.0>, {:exec, #Function<0.85613849/0 in AeCanary.Mdw.Cache.Service.Exchange.refresh_data/1>}, :infinity)
app                |     ** (EXIT) an exception was raised:
app                |         ** (MatchError) no match of right hand side value: {:error_code, 502, ""}
app                |             (ae_canary 1.0.0) lib/ae_canary/mdw/cache/service/exchange.ex:21: AeCanary.Mdw.Cache.Service.Exchange.refresh/1
app                |             (ae_canary 1.0.0) lib/ae_canary/mdw/worker.ex:13: AeCanary.Mdw.Worker.handle_call/3
app                |             (stdlib 3.14.1) gen_server.erl:715: :gen_server.try_handle_call/4
app                |             (stdlib 3.14.1) gen_server.erl:744: :gen_server.handle_msg/6
app                |             (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
app                |     (elixir 1.11.4) lib/gen_server.ex:1027: GenServer.call/3
```

**Comment by fabiankrol** [comment]
```
[error] GenServer #PID<0.8514.0> terminating
** (MatchError) no match of right hand side value: {:error, :nxdomain}
    (ae_canary 1.0.0) lib/ae_canary/mdw/cache/service/idle_detector.ex:16: AeCanary.Mdw.Cache.Service.IdleDetector.refresh/1
    (ae_canary 1.0.0) lib/ae_canary/mdw/worker.ex:13: AeCanary.Mdw.Worker.handle_call/3
    (stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
    (stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.8516.0>): {:exec, #Function<1.107928126/0 in AeCanary.Mdw.Cache.Service.IdleDetector.refresh_data/1>}
State: nil
Client #PID<0.8516.0> is alive

    (stdlib 3.13.2) gen.erl:208: :gen.do_call/4
    (elixir 1.12.3) lib/gen_server.ex:1021: GenServer.call/3
    (poolboy 1.5.2) /Users/fabian/Work/ae/ae_canary/deps/poolboy/src/poolboy.erl:84: :poolboy.transaction/3
    (ae_canary 1.0.0) lib/ae_canary/mdw.ex:25: anonymous fn/2 in AeCanary.Mdw.async_fetch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[error] Task #PID<0.8516.0> started from AeCanary.Mdw.Cache.Service.IdleDetector terminating
** (stop) exited in: GenServer.call(#PID<0.8514.0>, {:exec, #Function<1.107928126/0 in AeCanary.Mdw.Cache.Service.IdleDetector.refresh_data/1>}, :infinity)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :nxdomain}
            (ae_canary 1.0.0) lib/ae_canary/mdw/cache/service/idle_detector.ex:16: AeCanary.Mdw.Cache.Service.IdleDetector.refresh/1
            (ae_canary 1.0.0) lib/ae_canary/mdw/worker.ex:13: AeCanary.Mdw.Worker.handle_call/3
            (stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
            (stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
            (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.12.3) lib/gen_server.ex:1024: GenServer.call/3
    (poolboy 1.5.2) /Users/fabian/Work/ae/ae_canary/deps/poolboy/src/poolboy.erl:84: :poolboy.transaction/3
    (ae_canary 1.0.0) lib/ae_canary/mdw.ex:25: anonymous fn/2 in AeCanary.Mdw.async_fetch/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.15417525/0 in AeCanary.Mdw.async_fetch/2>
    Args: []
```
