### ISSUE TITLE
nil given for :keyHash

### ISSUE THREAD

**Issue by fabiankrol** [aeternity/ae_canary#34]
```
** (ArgumentError) nil given for :keyHash. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.keyHash)
    (ecto 3.6.1) lib/ecto/query/builder/filter.ex:161: Ecto.Query.Builder.Filter.kw!/7
    (ecto 3.6.1) lib/ecto/query/builder/filter.ex:154: Ecto.Query.Builder.Filter.kw!/3
    (ecto 3.6.1) lib/ecto/query/builder/filter.ex:120: Ecto.Query.Builder.Filter.filter!/6
    (ecto 3.6.1) lib/ecto/query/builder/filter.ex:148: Ecto.Query.Builder.Filter.filter!/7
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:76: Ecto.Repo.Queryable.get_by!/4
    (ae_canary 1.0.0) lib/ae_canary/fork_monitor/model.ex:35: AeCanary.ForkMonitor.Model.keyblocks_above_height/3
    (ae_canary 1.0.0) lib/ae_canary/fork_monitor/model/transaction_walker.ex:29: AeCanary.ForkMonitor.Model.TransactionWalker.update_spend_transactions_from_chain_end/1
    (ae_canary 1.0.0) lib/ae_canary/fork_monitor/model/chain_walker.ex:79: AeCanary.ForkMonitor.Model.ChainWalker.updateChainEnds/2
    ```

**Comment by fabiankrol** [comment]
blocker for: Use node api for services #28

**Comment by fabiankrol** [comment]
Fixed in: https://github.com/aeternity/ae_canary/pull/28/files#diff-468df14cb28d1f1aa12e0ccb1db49d38cfdd66ea2d44ca8fbf78dca93a6a1ad0R34
