### ISSUE TITLE
AeCanary.ForkMonitor.SyncService ecto crash

### ISSUE THREAD

**Issue by fabiankrol** [aeternity/ae_canary#35]
```
[error] Task #PID<0.846.0> started from AeCanary.ForkMonitor.SyncService terminating
** (Ecto.NoResultsError) expected at least one result but got none in query:

from b0 in AeCanary.ForkMonitor.Model.Block,
  where: b0.keyHash == ^"kh_5wYqiUhFsn8Gs8PBDJwyrJpobcMW5xPapa34pStgrxq8HqLUa"

    (ecto 3.6.1) lib/ecto/repo/queryable.ex:161: Ecto.Repo.Queryable.one!/3
    (ae_canary 1.0.0) lib/ae_canary/fork_monitor/model/transaction_walker.ex:61: AeCanary.ForkMonitor.Model.TransactionWalker.insert_spend_transactions/2
    (ae_canary 1.0.0) lib/ae_canary/fork_monitor/model/chain_walker.ex:79: AeCanary.ForkMonitor.Model.ChainWalker.updateChainEnds/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &AeCanary.ForkMonitor.Model.ChainWalker.updateChainEnds/2
    Args: [50000, #PID<0.686.0>]
[error] Chain walker process crashed {%Ecto.NoResultsError{message: "expected at least one result but got none in query:\n\nfrom b0 in AeCanary.ForkMonitor.Model.Block,\n  where: b0.keyHash == ^\"kh_5wYqiUhFsn8Gs8PBDJwyrJpobcMW5xPapa34pStgrxq8HqLUa\"\n"}, [{Ecto.Repo.Queryable, :one!, 3, [file: 'lib/ecto/repo/queryable.ex', line: 161]}, {AeCanary.ForkMonitor.Model.TransactionWalker, :insert_spend_transactions, 2, [file: 'lib/ae_canary/fork_monitor/model/transaction_walker.ex', line: 61]}, {AeCanary.ForkMonitor.Model.ChainWalker, :updateChainEnds, 2, [file: 'lib/ae_canary/fork_monitor/model/chain_walker.ex', line: 79]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]
```

**Comment by fabiankrol** [comment]
blocker for: Use node api for services #28
